# Generated by Django 3.2.10 on 2022-01-13 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mood', models.CharField(choices=[('ANGR', 'angry'), ('AFRA', 'afraid'), ('ASTO', 'astonished'), ('EXCI', 'excited'), ('HAPP', 'happy'), ('FRUS', 'frustrated'), ('TENS', 'tense'), ('ALAR', 'alarmed'), ('DELI', 'delighted'), ('GLAD', 'glad'), ('DIST', 'distressed'), ('ANNO', 'annoyed'), ('NEUT', 'neutral'), ('PLEA', 'pleased'), ('CONT', 'content'), ('DEPR', 'depressed'), ('MISR', 'miserable'), ('SLEEP', 'sleepy'), ('ATEA', 'at ease'), ('SATI', 'satisfied'), ('BORE', 'bored'), ('SAD', 'sad'), ('TIRE', 'tired'), ('CALM', 'calm'), ('RELA', 'relaxed')], default='NEUT', max_length=24)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('include_wellbeing', models.BooleanField(blank=True, default=False, null=True)),
                ('wellbeing', models.IntegerField(blank=True, null=True)),
                ('previouswellbeing', models.IntegerField(blank=True, null=True)),
                ('loneliness', models.IntegerField(blank=True, null=True)),
                ('previousloneliness', models.IntegerField(blank=True, null=True)),
                ('spoketosomeone', models.BooleanField(blank=True, default=False, null=True)),
                ('spoketosomeone_who', models.CharField(blank=True, max_length=256, null=True)),
                ('hours_bed', models.IntegerField(blank=True, null=True)),
                ('hours_sofa', models.IntegerField(blank=True, null=True)),
                ('hours_kitchen', models.IntegerField(blank=True, null=True)),
                ('hours_garden', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Pastime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatdoing', models.CharField(blank=True, choices=[('', 'Unspecified'), ('TV', 'TV'), ('EXER', 'Exercise'), ('ART', 'Arts & Crafts'), ('COOK', 'Cooking'), ('READ', 'Reading'), ('SOC', 'Socialising'), ('GARD', 'Gardening'), ('COMP', 'Computer'), ('HYG', 'Hygiene'), ('CLEN', 'Cleaning'), ('VOL', 'Volunteering'), ('MUS', 'Music'), ('WORK', 'Working'), ('HELP', 'Helping'), ('OTHER', 'Other')], default='', max_length=5, null=True)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastimes', to='moods.moods')),
                ('whowith', models.ManyToManyField(to='user_profile.Supporter')),
            ],
        ),
    ]
